---
- name: Add zabbix repo
  dnf:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-{{ zabbix_version }}-2.el8.noarch.rpm
    state: present

- name: Install zabbix-agent
  dnf:
    name: zabbix-agent
    state: latest

- name: Set zabbix hostname for jira
  set_fact:
    zabbix_hostname: jira
  when: inventory_hostname in groups['application']

- name: Set zabbix hostname for postgres
  set_fact:
    zabbix_hostname: postgres
  when: inventory_hostname in groups['database']

- name: Setup zabbix-agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix_agentd.conf

- name: Open ports for agent
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 10050/tcp
    - 10051/tcp

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Start and enable zabbix-agent service
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
  when: inventory_hostname in groups['production']

- name: Stop and disable zabbix-agent service
  systemd:
    name: zabbix-agent
    state: stopped
    enabled: no
  when: inventory_hostname in groups['staging']
...
